### ISSUE TITLE
[野火]《STM32 HAL库开发实战指南》系列 链接失效

### ISSUE THREAD

**Issue by leven99** [Embdefire/products#2]
野火开源图书专栏 - [野火]《STM32 HAL库开发实战指南》系列：http://t.cn/EKbzGds 的链接已失效

**Comment by NikolaDi** [comment]
https://github.com/Embdefire/products/wiki/%5B野火%5D《emWin实战指南》系列

此链接也失效了

**Comment by flyleaf91** [comment]
野火所有产品资料的下载链接已转移至地址：http://products.embedfire.com
